version: '3'

services:

  web:
    build: .
    command: >
            bash -c "python manage.py runserver 0.0.0.0:8000
                    & python manage.py rqworker default --with-scheduler"
    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media
    ports:
      - ${PORT}:8000
    depends_on:
      - db

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis
      - redis-conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  redis-data:
  redis-conf: